#!/usr/bin/env python3
"""Collect every result into results/summary.md.

    scripts/report.py

Reads results/scores/: <model>.summary.json (scored samples),
<model>.repaired.summary.json (after one repair round), <model>.vote.json
(selection methods), pooled.compare.json (significance across models) and
calibration.json. Do not edit summary.md by hand.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCORES = ROOT / "results" / "scores"

MODELS = [  # (results name, display name, samples per task)
    ("qwen3-8b", "Qwen3-8B", 8),
    ("codev-sva-8b", "CodeV-SVA-8B (SVA specialist)", 8),
    ("qwen3.8-27b", "Qwen3.8-27B (FP8)", 4),
]
SUITE_NAMES = {"human": "Human (62)", "machine": "Machine (276)",
               "human_codev": "Human, corrected (57)", "machine_codev": "Machine, corrected (269)"}


def load(name: str):
    path = SCORES / name
    return json.loads(path.read_text()) if path.exists() else None


def main():
    L = ["# Results", "",
         "Generated by `scripts/report.py` from `results/scores/`. Do not edit by hand.", "",
         "**Func@1** is the expected fraction of tasks on which one sampled answer is proven "
         "equivalent to the reference. Scored on the tasks the checker can decide: 62 human and "
         "276 machine tasks of FVEval (see README). All models ran in thinking mode, T=0.8, "
         "top-p 0.95, up to 16,384 new tokens.", ""]

    L += ["## Models on FVEval", "",
          "| Model | Samples | Suite | Compiles@1 | Func@1 | Func@1 after repair | Relaxed@1 | pass@n |",
          "|---|---|---|---|---|---|---|---|"]
    for key, label, n in MODELS:
        s, r = load(f"{key}.summary.json"), load(f"{key}.repaired.summary.json")
        if not s:
            continue
        for suite in ("human", "machine"):
            m = s["suites"][suite]
            rep = (r or {}).get("suites", {}).get(suite, {})
            L.append(f"| {label} | {n} | {SUITE_NAMES[suite]} | {m['syntax@1']} | **{m['equivalent@1']}** | "
                     f"{rep.get('equivalent@1', '-')} | {m['relaxed@1']} | {m[f'equivalent@{n}']} |")

    cal = load("calibration.json")
    if cal:
        L += ["", "## Calibration against Jasper", "",
              "Qwen3-8B on the CodeV-SVA authors' corrected version of FVEval, with their prompts, "
              "4 samples per task. Published values are theirs, scored with Cadence Jasper on all "
              "73 / 283 tasks. 95% intervals are bootstrap over tasks.", "",
              "| Suite | Func@1, this scorer (EBMC) | 95% CI | Published (Jasper) |", "|---|---|---|---|"]
        for suite, c in cal.items():
            L.append(f"| {SUITE_NAMES[suite]} | **{c['func_at_1']}** | [{c['ci95'][0]}, {c['ci95'][1]}] | "
                     f"{c['published']} |")

    L += ["", "## Choosing an answer without the reference", "",
          "Each method picks one of a task's samples. Columns give the fraction of tasks where the "
          "pick is equivalent to the reference. *Compiling sample*: a random sample that "
          "elaborates. *Text vote*: majority by identical text among those. *Semantic vote*: "
          "majority by proven equivalence among those.", "",
          "| Model | Suite | Random sample | Compiling sample | Text vote | Semantic vote | Any sample |",
          "|---|---|---|---|---|---|---|"]
    for key, label, _ in MODELS:
        v = load(f"{key}.vote.json")
        if not v:
            continue
        for suite, m in v["suites"].items():
            L.append(f"| {label} | {SUITE_NAMES[suite]} | {m['single_sample_equivalent']} | "
                     f"{m['compiling_sample_equivalent']} | {m['text_vote_equivalent']} | "
                     f"**{m['voted_equivalent']}** | {m['any_sample_equivalent']} |")

    pooled = load("pooled.compare.json")
    if pooled:
        L += ["", "### Significance, pooled over the three models", "",
              "Bootstrap over tasks (10,000 resamples); a resampled task brings all three models' "
              "outcomes for it. p is the fraction of resamples with a difference <= 0.", "",
              "| Difference | Suite | Points | 95% CI | p |", "|---|---|---|---|---|"]
        for suite in ("human", "machine"):
            for name, d in pooled[suite].items():
                if isinstance(d, dict):
                    L.append(f"| {name} | {SUITE_NAMES[suite]} | {d['diff']:+} | "
                             f"[{d['ci95'][0]:+}, {d['ci95'][1]:+}] | {d['p_le_0']} |")

    out = ROOT / "results" / "summary.md"
    out.write_text("\n".join(L) + "\n")
    print(out.read_text())


if __name__ == "__main__":
    main()
